### PR TITLE
Add support for custom references path to be used with CI

### PR DESCRIPTION
**Pull request by straris**
1) Run the tests as usually to generate your references
2) Add `"globals": {"customScreenshotsPath":"yourPath"}` to your nightwatch.json the path of your image references. e.g.
"test_settings": {
    "yourEnvironment": {
      "globals": {
        "customScreenshotsPath": "referenceScreenshots/"}}}
3) Run the tests again against the static references

### CODE REVIEW

**Comment by straris** [comment]
@pateketrueke let me know if something different is required here

**Comment by pateketrueke** [comment]
Being pragmatic I'm OK with your changes, but personally I think it can be cleaned up, a bit refactor does not hurts.

Also, I was thinking on the ability of changing this settings directly from the test code, and not from settings, because if you want different paths on runtime it can't be possible.

If you think we can proceed as is I'll merge your code asap.

Thanks for your feedback!

**Comment by straris** [comment]
@pateketrueke thank you for the constructive feedback, the reason I added it in the settings is for the use case of parallel runs or different environments. Different paths can be defined for each environment allowing the parallel execution on any number of paths.
Can't think of an example use case for dynamically changing the path but it's also still morning. Do you have something specific in mind?

**Comment by pateketrueke** [comment]
Nothing specific, yet. So let's merge this!

**Pull request merged**
